// Generated by gencpp from file disposing_vision/coordinate_normal.msg
// DO NOT EDIT!


#ifndef DISPOSING_VISION_MESSAGE_COORDINATE_NORMAL_H
#define DISPOSING_VISION_MESSAGE_COORDINATE_NORMAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace disposing_vision
{
template <class ContainerAllocator>
struct coordinate_normal_
{
  typedef coordinate_normal_<ContainerAllocator> Type;

  coordinate_normal_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
    }
  coordinate_normal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _normal_x_type;
  _normal_x_type normal_x;

   typedef float _normal_y_type;
  _normal_y_type normal_y;

   typedef float _normal_z_type;
  _normal_z_type normal_z;





  typedef boost::shared_ptr< ::disposing_vision::coordinate_normal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::disposing_vision::coordinate_normal_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_normal_

typedef ::disposing_vision::coordinate_normal_<std::allocator<void> > coordinate_normal;

typedef boost::shared_ptr< ::disposing_vision::coordinate_normal > coordinate_normalPtr;
typedef boost::shared_ptr< ::disposing_vision::coordinate_normal const> coordinate_normalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::disposing_vision::coordinate_normal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::disposing_vision::coordinate_normal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::disposing_vision::coordinate_normal_<ContainerAllocator1> & lhs, const ::disposing_vision::coordinate_normal_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.normal_x == rhs.normal_x &&
    lhs.normal_y == rhs.normal_y &&
    lhs.normal_z == rhs.normal_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::disposing_vision::coordinate_normal_<ContainerAllocator1> & lhs, const ::disposing_vision::coordinate_normal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace disposing_vision

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::disposing_vision::coordinate_normal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::disposing_vision::coordinate_normal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::disposing_vision::coordinate_normal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee0ea2f53dcc000e5f2603d8a2d15279";
  }

  static const char* value(const ::disposing_vision::coordinate_normal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee0ea2f53dcc000eULL;
  static const uint64_t static_value2 = 0x5f2603d8a2d15279ULL;
};

template<class ContainerAllocator>
struct DataType< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "disposing_vision/coordinate_normal";
  }

  static const char* value(const ::disposing_vision::coordinate_normal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 normal_x\n"
"float32 normal_y\n"
"float32 normal_z\n"
;
  }

  static const char* value(const ::disposing_vision::coordinate_normal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.normal_x);
      stream.next(m.normal_y);
      stream.next(m.normal_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_normal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::disposing_vision::coordinate_normal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::disposing_vision::coordinate_normal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "normal_x: ";
    Printer<float>::stream(s, indent + "  ", v.normal_x);
    s << indent << "normal_y: ";
    Printer<float>::stream(s, indent + "  ", v.normal_y);
    s << indent << "normal_z: ";
    Printer<float>::stream(s, indent + "  ", v.normal_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DISPOSING_VISION_MESSAGE_COORDINATE_NORMAL_H
