// Generated by gencpp from file getcalue/Selective_Search_srvResponse.msg
// DO NOT EDIT!


#ifndef GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVRESPONSE_H
#define GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace getcalue
{
template <class ContainerAllocator>
struct Selective_Search_srvResponse_
{
  typedef Selective_Search_srvResponse_<ContainerAllocator> Type;

  Selective_Search_srvResponse_()
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , depth(0.0)  {
    }
  Selective_Search_srvResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , w(0.0)
    , h(0.0)
    , depth(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _w_type;
  _w_type w;

   typedef float _h_type;
  _h_type h;

   typedef float _depth_type;
  _depth_type depth;





  typedef boost::shared_ptr< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Selective_Search_srvResponse_

typedef ::getcalue::Selective_Search_srvResponse_<std::allocator<void> > Selective_Search_srvResponse;

typedef boost::shared_ptr< ::getcalue::Selective_Search_srvResponse > Selective_Search_srvResponsePtr;
typedef boost::shared_ptr< ::getcalue::Selective_Search_srvResponse const> Selective_Search_srvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator1> & lhs, const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.w == rhs.w &&
    lhs.h == rhs.h &&
    lhs.depth == rhs.depth;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator1> & lhs, const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace getcalue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ce212d18c694b98ebe7f905c8e5ab43f";
  }

  static const char* value(const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xce212d18c694b98eULL;
  static const uint64_t static_value2 = 0xbe7f905c8e5ab43fULL;
};

template<class ContainerAllocator>
struct DataType< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "getcalue/Selective_Search_srvResponse";
  }

  static const char* value(const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 w\n"
"float32 h\n"
"float32 depth\n"
"\n"
;
  }

  static const char* value(const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
      stream.next(m.depth);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Selective_Search_srvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::getcalue::Selective_Search_srvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::getcalue::Selective_Search_srvResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVRESPONSE_H
