// Generated by gencpp from file getcalue/Selective_Search_srv.msg
// DO NOT EDIT!


#ifndef GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRV_H
#define GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRV_H

#include <ros/service_traits.h>


#include <getcalue/Selective_Search_srvRequest.h>
#include <getcalue/Selective_Search_srvResponse.h>


namespace getcalue
{

struct Selective_Search_srv
{

typedef Selective_Search_srvRequest Request;
typedef Selective_Search_srvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Selective_Search_srv
} // namespace getcalue


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::getcalue::Selective_Search_srv > {
  static const char* value()
  {
    return "18c14c3bda66d95b24244dd6b7b2ba3f";
  }

  static const char* value(const ::getcalue::Selective_Search_srv&) { return value(); }
};

template<>
struct DataType< ::getcalue::Selective_Search_srv > {
  static const char* value()
  {
    return "getcalue/Selective_Search_srv";
  }

  static const char* value(const ::getcalue::Selective_Search_srv&) { return value(); }
};


// service_traits::MD5Sum< ::getcalue::Selective_Search_srvRequest> should match
// service_traits::MD5Sum< ::getcalue::Selective_Search_srv >
template<>
struct MD5Sum< ::getcalue::Selective_Search_srvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::getcalue::Selective_Search_srv >::value();
  }
  static const char* value(const ::getcalue::Selective_Search_srvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::getcalue::Selective_Search_srvRequest> should match
// service_traits::DataType< ::getcalue::Selective_Search_srv >
template<>
struct DataType< ::getcalue::Selective_Search_srvRequest>
{
  static const char* value()
  {
    return DataType< ::getcalue::Selective_Search_srv >::value();
  }
  static const char* value(const ::getcalue::Selective_Search_srvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::getcalue::Selective_Search_srvResponse> should match
// service_traits::MD5Sum< ::getcalue::Selective_Search_srv >
template<>
struct MD5Sum< ::getcalue::Selective_Search_srvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::getcalue::Selective_Search_srv >::value();
  }
  static const char* value(const ::getcalue::Selective_Search_srvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::getcalue::Selective_Search_srvResponse> should match
// service_traits::DataType< ::getcalue::Selective_Search_srv >
template<>
struct DataType< ::getcalue::Selective_Search_srvResponse>
{
  static const char* value()
  {
    return DataType< ::getcalue::Selective_Search_srv >::value();
  }
  static const char* value(const ::getcalue::Selective_Search_srvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRV_H
