// Generated by gencpp from file getcalue/Selective_Search_srvRequest.msg
// DO NOT EDIT!


#ifndef GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVREQUEST_H
#define GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace getcalue
{
template <class ContainerAllocator>
struct Selective_Search_srvRequest_
{
  typedef Selective_Search_srvRequest_<ContainerAllocator> Type;

  Selective_Search_srvRequest_()
    : input(0)  {
    }
  Selective_Search_srvRequest_(const ContainerAllocator& _alloc)
    : input(0)  {
  (void)_alloc;
    }



   typedef int64_t _input_type;
  _input_type input;





  typedef boost::shared_ptr< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Selective_Search_srvRequest_

typedef ::getcalue::Selective_Search_srvRequest_<std::allocator<void> > Selective_Search_srvRequest;

typedef boost::shared_ptr< ::getcalue::Selective_Search_srvRequest > Selective_Search_srvRequestPtr;
typedef boost::shared_ptr< ::getcalue::Selective_Search_srvRequest const> Selective_Search_srvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator1> & lhs, const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input == rhs.input;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator1> & lhs, const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace getcalue

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "efb1911a9ea9163151d70e4586fa0801";
  }

  static const char* value(const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xefb1911a9ea91631ULL;
  static const uint64_t static_value2 = 0x51d70e4586fa0801ULL;
};

template<class ContainerAllocator>
struct DataType< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "getcalue/Selective_Search_srvRequest";
  }

  static const char* value(const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 input\n"
;
  }

  static const char* value(const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Selective_Search_srvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::getcalue::Selective_Search_srvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::getcalue::Selective_Search_srvRequest_<ContainerAllocator>& v)
  {
    s << indent << "input: ";
    Printer<int64_t>::stream(s, indent + "  ", v.input);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GETCALUE_MESSAGE_SELECTIVE_SEARCH_SRVREQUEST_H
