// Generated by gencpp from file ROS_Socket/arm_state.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_ARM_STATE_H
#define ROS_SOCKET_MESSAGE_ARM_STATE_H

#include <ros/service_traits.h>


#include <ROS_Socket/arm_stateRequest.h>
#include <ROS_Socket/arm_stateResponse.h>


namespace ROS_Socket
{

struct arm_state
{

typedef arm_stateRequest Request;
typedef arm_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct arm_state
} // namespace ROS_Socket


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ROS_Socket::arm_state > {
  static const char* value()
  {
    return "9a18ae858978714c254ecb02ef2924b7";
  }

  static const char* value(const ::ROS_Socket::arm_state&) { return value(); }
};

template<>
struct DataType< ::ROS_Socket::arm_state > {
  static const char* value()
  {
    return "ROS_Socket/arm_state";
  }

  static const char* value(const ::ROS_Socket::arm_state&) { return value(); }
};


// service_traits::MD5Sum< ::ROS_Socket::arm_stateRequest> should match
// service_traits::MD5Sum< ::ROS_Socket::arm_state >
template<>
struct MD5Sum< ::ROS_Socket::arm_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_Socket::arm_state >::value();
  }
  static const char* value(const ::ROS_Socket::arm_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_Socket::arm_stateRequest> should match
// service_traits::DataType< ::ROS_Socket::arm_state >
template<>
struct DataType< ::ROS_Socket::arm_stateRequest>
{
  static const char* value()
  {
    return DataType< ::ROS_Socket::arm_state >::value();
  }
  static const char* value(const ::ROS_Socket::arm_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ROS_Socket::arm_stateResponse> should match
// service_traits::MD5Sum< ::ROS_Socket::arm_state >
template<>
struct MD5Sum< ::ROS_Socket::arm_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ROS_Socket::arm_state >::value();
  }
  static const char* value(const ::ROS_Socket::arm_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ROS_Socket::arm_stateResponse> should match
// service_traits::DataType< ::ROS_Socket::arm_state >
template<>
struct DataType< ::ROS_Socket::arm_stateResponse>
{
  static const char* value()
  {
    return DataType< ::ROS_Socket::arm_state >::value();
  }
  static const char* value(const ::ROS_Socket::arm_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_ARM_STATE_H
