// Generated by gencpp from file ROS_Socket/arm_stateRequest.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_ARM_STATEREQUEST_H
#define ROS_SOCKET_MESSAGE_ARM_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct arm_stateRequest_
{
  typedef arm_stateRequest_<ContainerAllocator> Type;

  arm_stateRequest_()
    : Arm_state(0)  {
    }
  arm_stateRequest_(const ContainerAllocator& _alloc)
    : Arm_state(0)  {
  (void)_alloc;
    }



   typedef int32_t _Arm_state_type;
  _Arm_state_type Arm_state;





  typedef boost::shared_ptr< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct arm_stateRequest_

typedef ::ROS_Socket::arm_stateRequest_<std::allocator<void> > arm_stateRequest;

typedef boost::shared_ptr< ::ROS_Socket::arm_stateRequest > arm_stateRequestPtr;
typedef boost::shared_ptr< ::ROS_Socket::arm_stateRequest const> arm_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::arm_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::arm_stateRequest_<ContainerAllocator1> & lhs, const ::ROS_Socket::arm_stateRequest_<ContainerAllocator2> & rhs)
{
  return lhs.Arm_state == rhs.Arm_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::arm_stateRequest_<ContainerAllocator1> & lhs, const ::ROS_Socket::arm_stateRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f8852739838bec3a3ae498184753087";
  }

  static const char* value(const ::ROS_Socket::arm_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f8852739838bec3ULL;
  static const uint64_t static_value2 = 0xa3ae498184753087ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/arm_stateRequest";
  }

  static const char* value(const ::ROS_Socket::arm_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 Arm_state\n"
;
  }

  static const char* value(const ::ROS_Socket::arm_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Arm_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::arm_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::arm_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "Arm_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.Arm_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_ARM_STATEREQUEST_H
