// Generated by gencpp from file ROS_Socket/arm_dataResponse.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_ARM_DATARESPONSE_H
#define ROS_SOCKET_MESSAGE_ARM_DATARESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct arm_dataResponse_
{
  typedef arm_dataResponse_<ContainerAllocator> Type;

  arm_dataResponse_()
    : response(0)  {
    }
  arm_dataResponse_(const ContainerAllocator& _alloc)
    : response(0)  {
  (void)_alloc;
    }



   typedef int32_t _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> const> ConstPtr;

}; // struct arm_dataResponse_

typedef ::ROS_Socket::arm_dataResponse_<std::allocator<void> > arm_dataResponse;

typedef boost::shared_ptr< ::ROS_Socket::arm_dataResponse > arm_dataResponsePtr;
typedef boost::shared_ptr< ::ROS_Socket::arm_dataResponse const> arm_dataResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::arm_dataResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::arm_dataResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::arm_dataResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::arm_dataResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::arm_dataResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f45f68e2feefb1307598e828e260b7d7";
  }

  static const char* value(const ::ROS_Socket::arm_dataResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf45f68e2feefb130ULL;
  static const uint64_t static_value2 = 0x7598e828e260b7d7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/arm_dataResponse";
  }

  static const char* value(const ::ROS_Socket::arm_dataResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 response\n"
"\n"
;
  }

  static const char* value(const ::ROS_Socket::arm_dataResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct arm_dataResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::arm_dataResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::arm_dataResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<int32_t>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_ARM_DATARESPONSE_H
