// Generated by gencpp from file ROS_Socket/grip_modeResponse.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_GRIP_MODERESPONSE_H
#define ROS_SOCKET_MESSAGE_GRIP_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct grip_modeResponse_
{
  typedef grip_modeResponse_<ContainerAllocator> Type;

  grip_modeResponse_()
    : grip_feedback(0)  {
    }
  grip_modeResponse_(const ContainerAllocator& _alloc)
    : grip_feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _grip_feedback_type;
  _grip_feedback_type grip_feedback;





  typedef boost::shared_ptr< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct grip_modeResponse_

typedef ::ROS_Socket::grip_modeResponse_<std::allocator<void> > grip_modeResponse;

typedef boost::shared_ptr< ::ROS_Socket::grip_modeResponse > grip_modeResponsePtr;
typedef boost::shared_ptr< ::ROS_Socket::grip_modeResponse const> grip_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::grip_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::grip_modeResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::grip_modeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.grip_feedback == rhs.grip_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::grip_modeResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::grip_modeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd85edbf9714b6716896d2eb254e1e0d";
  }

  static const char* value(const ::ROS_Socket::grip_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd85edbf9714b671ULL;
  static const uint64_t static_value2 = 0x6896d2eb254e1e0dULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/grip_modeResponse";
  }

  static const char* value(const ::ROS_Socket::grip_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 grip_feedback\n"
"\n"
;
  }

  static const char* value(const ::ROS_Socket::grip_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grip_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grip_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::grip_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::grip_modeResponse_<ContainerAllocator>& v)
  {
    s << indent << "grip_feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grip_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_GRIP_MODERESPONSE_H
