// Generated by gencpp from file ROS_Socket/ROI_array.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_ROI_ARRAY_H
#define ROS_SOCKET_MESSAGE_ROI_ARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <ROS_Socket/ROI.h>

namespace ROS_Socket
{
template <class ContainerAllocator>
struct ROI_array_
{
  typedef ROI_array_<ContainerAllocator> Type;

  ROI_array_()
    : ROI_list()  {
    }
  ROI_array_(const ContainerAllocator& _alloc)
    : ROI_list(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::ROS_Socket::ROI_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ROS_Socket::ROI_<ContainerAllocator> >::other >  _ROI_list_type;
  _ROI_list_type ROI_list;





  typedef boost::shared_ptr< ::ROS_Socket::ROI_array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::ROI_array_<ContainerAllocator> const> ConstPtr;

}; // struct ROI_array_

typedef ::ROS_Socket::ROI_array_<std::allocator<void> > ROI_array;

typedef boost::shared_ptr< ::ROS_Socket::ROI_array > ROI_arrayPtr;
typedef boost::shared_ptr< ::ROS_Socket::ROI_array const> ROI_arrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::ROI_array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::ROI_array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::ROI_array_<ContainerAllocator1> & lhs, const ::ROS_Socket::ROI_array_<ContainerAllocator2> & rhs)
{
  return lhs.ROI_list == rhs.ROI_list;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::ROI_array_<ContainerAllocator1> & lhs, const ::ROS_Socket::ROI_array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::ROI_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::ROI_array_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::ROI_array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::ROI_array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::ROI_array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::ROI_array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "830846477b2f91488efcf13bb1eeda9f";
  }

  static const char* value(const ::ROS_Socket::ROI_array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x830846477b2f9148ULL;
  static const uint64_t static_value2 = 0x8efcf13bb1eeda9fULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/ROI_array";
  }

  static const char* value(const ::ROS_Socket::ROI_array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::ROI_array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROI[] ROI_list\n"
"\n"
"================================================================================\n"
"MSG: ROS_Socket/ROI\n"
"string object_name\n"
"float32 score\n"
"int32 min_x\n"
"int32 Max_x\n"
"int32 min_y\n"
"int32 Max_y\n"
;
  }

  static const char* value(const ::ROS_Socket::ROI_array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::ROI_array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ROI_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ROI_array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::ROI_array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::ROI_array_<ContainerAllocator>& v)
  {
    s << indent << "ROI_list[]" << std::endl;
    for (size_t i = 0; i < v.ROI_list.size(); ++i)
    {
      s << indent << "  ROI_list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ROS_Socket::ROI_<ContainerAllocator> >::stream(s, indent + "    ", v.ROI_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_ROI_ARRAY_H
