// Generated by gencpp from file ROS_Socket/sent_flagResponse.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_SENT_FLAGRESPONSE_H
#define ROS_SOCKET_MESSAGE_SENT_FLAGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct sent_flagResponse_
{
  typedef sent_flagResponse_<ContainerAllocator> Type;

  sent_flagResponse_()
    : sent_flag_feedback(0)  {
    }
  sent_flagResponse_(const ContainerAllocator& _alloc)
    : sent_flag_feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _sent_flag_feedback_type;
  _sent_flag_feedback_type sent_flag_feedback;





  typedef boost::shared_ptr< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> const> ConstPtr;

}; // struct sent_flagResponse_

typedef ::ROS_Socket::sent_flagResponse_<std::allocator<void> > sent_flagResponse;

typedef boost::shared_ptr< ::ROS_Socket::sent_flagResponse > sent_flagResponsePtr;
typedef boost::shared_ptr< ::ROS_Socket::sent_flagResponse const> sent_flagResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::sent_flagResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::sent_flagResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::sent_flagResponse_<ContainerAllocator2> & rhs)
{
  return lhs.sent_flag_feedback == rhs.sent_flag_feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::sent_flagResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::sent_flagResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b8c58d190b336cb3e72a77db8ef8d99";
  }

  static const char* value(const ::ROS_Socket::sent_flagResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b8c58d190b336cbULL;
  static const uint64_t static_value2 = 0x3e72a77db8ef8d99ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/sent_flagResponse";
  }

  static const char* value(const ::ROS_Socket::sent_flagResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sent_flag_feedback\n"
"\n"
;
  }

  static const char* value(const ::ROS_Socket::sent_flagResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sent_flag_feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sent_flagResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::sent_flagResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::sent_flagResponse_<ContainerAllocator>& v)
  {
    s << indent << "sent_flag_feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sent_flag_feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_SENT_FLAGRESPONSE_H
