// Generated by gencpp from file ROS_Socket/sent_flagRequest.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_SENT_FLAGREQUEST_H
#define ROS_SOCKET_MESSAGE_SENT_FLAGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct sent_flagRequest_
{
  typedef sent_flagRequest_<ContainerAllocator> Type;

  sent_flagRequest_()
    : sent_flag(0)  {
    }
  sent_flagRequest_(const ContainerAllocator& _alloc)
    : sent_flag(0)  {
  (void)_alloc;
    }



   typedef int32_t _sent_flag_type;
  _sent_flag_type sent_flag;





  typedef boost::shared_ptr< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> const> ConstPtr;

}; // struct sent_flagRequest_

typedef ::ROS_Socket::sent_flagRequest_<std::allocator<void> > sent_flagRequest;

typedef boost::shared_ptr< ::ROS_Socket::sent_flagRequest > sent_flagRequestPtr;
typedef boost::shared_ptr< ::ROS_Socket::sent_flagRequest const> sent_flagRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::sent_flagRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::sent_flagRequest_<ContainerAllocator1> & lhs, const ::ROS_Socket::sent_flagRequest_<ContainerAllocator2> & rhs)
{
  return lhs.sent_flag == rhs.sent_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::sent_flagRequest_<ContainerAllocator1> & lhs, const ::ROS_Socket::sent_flagRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39e05f3ce9098d0387c45debbe323a10";
  }

  static const char* value(const ::ROS_Socket::sent_flagRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39e05f3ce9098d03ULL;
  static const uint64_t static_value2 = 0x87c45debbe323a10ULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/sent_flagRequest";
  }

  static const char* value(const ::ROS_Socket::sent_flagRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 sent_flag\n"
;
  }

  static const char* value(const ::ROS_Socket::sent_flagRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sent_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct sent_flagRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::sent_flagRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::sent_flagRequest_<ContainerAllocator>& v)
  {
    s << indent << "sent_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sent_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_SENT_FLAGREQUEST_H
