// Generated by gencpp from file ROS_Socket/speed_modeResponse.msg
// DO NOT EDIT!


#ifndef ROS_SOCKET_MESSAGE_SPEED_MODERESPONSE_H
#define ROS_SOCKET_MESSAGE_SPEED_MODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ROS_Socket
{
template <class ContainerAllocator>
struct speed_modeResponse_
{
  typedef speed_modeResponse_<ContainerAllocator> Type;

  speed_modeResponse_()
    : feedback(0)  {
    }
  speed_modeResponse_(const ContainerAllocator& _alloc)
    : feedback(0)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct speed_modeResponse_

typedef ::ROS_Socket::speed_modeResponse_<std::allocator<void> > speed_modeResponse;

typedef boost::shared_ptr< ::ROS_Socket::speed_modeResponse > speed_modeResponsePtr;
typedef boost::shared_ptr< ::ROS_Socket::speed_modeResponse const> speed_modeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ROS_Socket::speed_modeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ROS_Socket::speed_modeResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::speed_modeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.feedback == rhs.feedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ROS_Socket::speed_modeResponse_<ContainerAllocator1> & lhs, const ::ROS_Socket::speed_modeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ROS_Socket

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "49ceb5b32ea3af22073ede4a0328249e";
  }

  static const char* value(const ::ROS_Socket::speed_modeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x49ceb5b32ea3af22ULL;
  static const uint64_t static_value2 = 0x073ede4a0328249eULL;
};

template<class ContainerAllocator>
struct DataType< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ROS_Socket/speed_modeResponse";
  }

  static const char* value(const ::ROS_Socket::speed_modeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 feedback\n"
"\n"
;
  }

  static const char* value(const ::ROS_Socket::speed_modeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_modeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ROS_Socket::speed_modeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ROS_Socket::speed_modeResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_SOCKET_MESSAGE_SPEED_MODERESPONSE_H
