// Generated by gencpp from file mask_rcnn/coordinate_normal.msg
// DO NOT EDIT!


#ifndef MASK_RCNN_MESSAGE_COORDINATE_NORMAL_H
#define MASK_RCNN_MESSAGE_COORDINATE_NORMAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mask_rcnn
{
template <class ContainerAllocator>
struct coordinate_normal_
{
  typedef coordinate_normal_<ContainerAllocator> Type;

  coordinate_normal_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
    }
  coordinate_normal_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , normal_x(0.0)
    , normal_y(0.0)
    , normal_z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _normal_x_type;
  _normal_x_type normal_x;

   typedef float _normal_y_type;
  _normal_y_type normal_y;

   typedef float _normal_z_type;
  _normal_z_type normal_z;





  typedef boost::shared_ptr< ::mask_rcnn::coordinate_normal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mask_rcnn::coordinate_normal_<ContainerAllocator> const> ConstPtr;

}; // struct coordinate_normal_

typedef ::mask_rcnn::coordinate_normal_<std::allocator<void> > coordinate_normal;

typedef boost::shared_ptr< ::mask_rcnn::coordinate_normal > coordinate_normalPtr;
typedef boost::shared_ptr< ::mask_rcnn::coordinate_normal const> coordinate_normalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mask_rcnn::coordinate_normal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mask_rcnn

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'mask_rcnn': ['/home/wei/Maskrcnn_ws/src/mask_rcnn_ros/mask_rcnn_ros/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mask_rcnn::coordinate_normal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mask_rcnn::coordinate_normal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mask_rcnn::coordinate_normal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ee0ea2f53dcc000e5f2603d8a2d15279";
  }

  static const char* value(const ::mask_rcnn::coordinate_normal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xee0ea2f53dcc000eULL;
  static const uint64_t static_value2 = 0x5f2603d8a2d15279ULL;
};

template<class ContainerAllocator>
struct DataType< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mask_rcnn/coordinate_normal";
  }

  static const char* value(const ::mask_rcnn::coordinate_normal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
float32 normal_x\n\
float32 normal_y\n\
float32 normal_z\n\
";
  }

  static const char* value(const ::mask_rcnn::coordinate_normal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.normal_x);
      stream.next(m.normal_y);
      stream.next(m.normal_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct coordinate_normal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mask_rcnn::coordinate_normal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mask_rcnn::coordinate_normal_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "normal_x: ";
    Printer<float>::stream(s, indent + "  ", v.normal_x);
    s << indent << "normal_y: ";
    Printer<float>::stream(s, indent + "  ", v.normal_y);
    s << indent << "normal_z: ";
    Printer<float>::stream(s, indent + "  ", v.normal_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MASK_RCNN_MESSAGE_COORDINATE_NORMAL_H
